### ISSUE TITLE
Request Source - Tenshi

### ISSUE THREAD

**Issue by adamxsv2** [naufaljct48/nopools-ext#1]
Halo, sebelumnya terimakasih bro udah ngebuatin source berbasis bahasa Indonesia. dibawah ini form request new web nya bro.

nama web: Tenshi
domain: https://tenshi.id/
bahasa: indonesia

Thanks🌟

**Comment by naufaljct48** [comment]
soon yaa ✌️

**Comment by adamxsv2** [comment]
> soon yaa ✌️

Thanks bro, btw komikcast sama shinigami broken ya? load nya 1/0 terus

**Comment by naufaljct48** [comment]
[Tenshi ](https://github.com/naufaljct48/nopools-ext/commit/6bc3a3f1ca3e004495eb52099619536916d3cb2e)done ya
Komikcast, Shinigami, Pojokmanga broken semua

**Comment by naufaljct48** [comment]
[Tenshi](https://github.com/naufaljct48/nopools-ext/commit/6bc3a3f1ca3e004495eb52099619536916d3cb2e)
